language: python
python:
  - 2.7

services:
  - mongodb

# command to install dependencies
install:
  - pip install -r requirements.txt


before_script:
  - mongo django_test --eval 'db.createUser({user:"admin",pwd:"password",roles:["userAdminAnyDatabase", "admin"]});'

# command to run tests
script:
  - python manage.py test
