HEADER_ID_FIELD = dict(
    TRANSACTION="Transaction_ID",
    CUSTOMER="User_ID",
    CONVERSION="Conversion_ID"
)

HEADER_OPTION = dict(
    TRANSACTION=[
        "Transaction_ID",
        "User_ID",
        "Transaction_Date",
        "Transaction_Quantity",
        "Transaction_Value",
        "Product_Measure",
        "Product_Size",
        "Brand",
        "Category",
        "Chain"
    ],
    CUSTOMER=[
        "User_ID",
        "Contact_Number",
        "Contact_Email",
        "Last_Name",
        "First_Name",
        "Display_Name",
        "Age",
        "Gender",
        "Address",
        "Country",
        "Create_Date",
        "Last_Modified_Date"
    ],
    CONVERSION=[
        "Conversion_ID",
        "Campaign_ID",
        "User_ID",
        "Response",
        "Transaction_ID"
    ],
    CAMPAIGN=[
        "Campaign_ID",
        "Channel_ID",
        "Campaign_Name",
        "Start_Date",
        "End_Date",
        "Spending",
        "Clicks",
        "Impressions"
    ],
    CHANNEL=[
        "Channel_ID",
        "Channel_Name",
        "Country",
        "Category"
    ],
    OFFLINE_EVENT=[
        "Event_ID",
        "Event_Type",
        "Start_Date",
        "End_Date"
    ],
    GOOGLE_ANALYTICS=[
        "User_City",
        "User_Type",
        "Source",
        "Last_Seen_Sessions",
        "Mobile_Device_Branding",
        "Browser",
        "Date"
    ],
    SERVICE_LOGS=[
        "Transaction_ID",
        "Timestamp",
        "Status",
        "Service_Name",
        "Service_Type",
        "Message"
    ],
    SUBSCRIPTION=[
        "User_Name",
        "Timestamp",
        "Subscription",
        "Action"
    ],
    PEOPLE_COUNTER_DATA=[
        "Timestamp",
        "Number_People_In",
        "Number_People_Out"
    ],
    MY_FACEBOOK=[
        "Timestamp",
        "Page_impressions",
        "Page_impressions_paid",
        "Page_impressions_organic",
        "Page_stories",
        "Page_engaged_users",
        "Page_negative_feedback",
        "Page_consumptions",
        "Page_fans",
        "Page_fans_locale",
        "Page_fans_city",
        "Page_fans_country",
        "Page_fan_adds",
        "Page_fan_adds_unique",
        "Page_views_total",
        "Page_video_views_10s"
    ],
    OPEN_DATA_WEATHER=[
        "Date",
        "Weather",
        "Temperature"
    ],
    OPEN_DATA_HOLIDAYS=[
        "Date",
        "Weekday",
        "Holiday_Type"
    ],
    OPEN_DATA_HUMAN_TRAFFIC=[
        "Timestamp",
        "Location",
        "Status",
        "Index/Ratio"
    ],
    COMPETITOR_FACEBOOK=[
        "Competitor",
        "Timestamp",
        "Page_Likes",
        "Followers",
        "People_talking_about"
    ]
)
